# Numpy Basics  <hr style = "border:2.5px solid #F29367"></hr>

Data Analyst: Sam T. Sabidalas <br>
Department: Electrical Engineering

In [8]:
# imports and packages
import numpy as np
from scipy import stats

# 1D Array

In [38]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

# 2D Array

In [42]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
my_array = my_array.T
my_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [50]:
np.sum(my_array, axis = 0)

array([ 6, 15])

In [53]:
np.sum(my_array, axis = 1)

array([5, 7, 9])

# Measures of Central Tendency

In [4]:
fruits = np.array([120,60,85,150,200])
fruits

array([120,  60,  85, 150, 200])

In [39]:
fruits_mean = np.mean(fruits)
fruits_mean
print(" The mean is " + str(fruits_mean))

 The mean is 123.0


In [40]:
median_fruits = np.median(fruits)
median_fruits
print(" The median is " + str(median_fruits))

 The median is 120.0


In [41]:
mode_fruits = stats.mode(fruits)
mode_fruits
print(" The mode is " + str(mode_fruits))

 The mode is ModeResult(mode=60, count=1)


# Jaguar vs Panther

## Jaguar

In [10]:
jaguar = np.array([10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8])
jaguar

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [26]:
jaguar_mean = np.mean(jaguar)
jaguar_mean
print( "The mean is " + str(jaguar_mean))

The mean is 9.399999999999999


In [28]:
median_jaguar = np.median(jaguar)
median_jaguar
print( "The median is " + str(median_jaguar))

The median is 9.8


In [54]:
mode_jaguar = stats.mode(jaguar)
mode_jaguar
print( "The mode is " + str(mode_jaguar))

The mode is ModeResult(mode=9.8, count=2)


In [61]:
max_jaguar = np.max(jaguar)
min_jaguar = np.min(jaguar)


range_jaguar = max_jaguar - min_jaguar
range_jaguar
print(" The range is " + str(range_jaguar))

 The range is 8.0


In [84]:
#Q1
q1_jaguar = np.percentile(jaguar,25)
q1_jaguar
print(" The 1st quartile is " + str(q1_jaguar))

 The 1st quartile is 9.4


In [83]:
#Q2
q2_jaguar = np.percentile(jaguar,50)
q2_jaguar
print(" The 2nd quartile is " + str(q2_jaguar))

 The 2nd quartile is 9.8


In [82]:
#Q3
q3_jaguar = np.percentile(jaguar,75)
q3_jaguar
print("The 3rd quartile is " + str(q3_jaguar))

The 3rd quartile is 10.45


In [68]:
#IQR
iqr_jaguar = q3_jaguar - q1_jaguar
iqr_jaguar
print("The Interquatile Range is " + str(iqr_jaguar))

The Interquatile Range is 1.049999999999999


In [69]:
#sample variance
var_jaguar = np.var(jaguar,ddof=1)
var_jaguar
print("The variance is " + str(var_jaguar))

The variance is 4.86


In [31]:
# sample standard deviation
samplestd_jaguar = np.std(jaguar,ddof=1)
samplestd_jaguar
print(" The sample standard deviation is " + str(samplestd_jaguar))

 The sample standard deviation is 2.2045407685048604


## Panther

In [18]:
panther = np.array([10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1])
panther

array([10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1])

In [32]:
panther_mean = np.mean(panther)
panther_mean
print( "The mean is " + str(panther_mean))

The mean is 10.75


In [33]:
median_panther = np.median(panther)
median_panther
print( "The median is " + str(median_panther))

The median is 9.55


In [ ]:
mode_panther = stats.mode(panther)
mode_panther
print( "The mode is " + str(mode_panther))

The mode is ModeResult(mode=9.1, count=3)


In [70]:
max_panther = np.max(panther)
min_panther = np.min(panther)


range_panther = max_panther - min_panther
range_panther
print(" The range is " + str(range_panther))

 The range is 10.9


In [81]:
#Q1
q1_panther = np.percentile(panther,25)
q1_panther
print(" The 1st quartile is " + str(q1_panther))

 The 1st quartile is 9.125


In [80]:
#Q2
q2_panther = np.percentile(panther,50)
q2_panther
print(" The 2nd quartile is " + str(q2_panther))

 The 2nd quartile is 9.55


In [79]:
#Q3
q3_panther = np.percentile(panther,75)
q3_panther
print(" The 3rd quartile is " + str(q3_panther))

 The 3rd quartile is 10.625


In [85]:
#IQR
iqr_panther = q3_panther - q1_panther
iqr_panther
print("The Interquatile Range is " + str(iqr_panther))

The Interquatile Range is 1.5


In [78]:
#sample variance
var_panther = np.var(panther,ddof=1)
var_panther
print("The variance is " + str(var_panther))

The variance is 11.082777777777777


In [36]:
# sample standard deviation
samplestd_panther = np.std(panther,ddof=1)
samplestd_panther
print(" The sample standard deviation is " + str(samplestd_panther))

 The sample standard deviation is 3.3290806204983645
